from flask import request
from helper.helperFunctions import build_response
from model.llm_client import call_llm
import json

SYSTEM_PROMPT = """
You are a chart configuration engine.

YOU MUST FOLLOW THESE RULES STRICTLY:

1. OUTPUT ONLY RAW JSON
2. NO markdown
3. NO explanation
4. NO text before or after JSON

You will receive:
- charts (list)
- user instruction

Your task:
- Identify the relevant chart(s)
- Apply ONLY view-level changes

ALLOWED:
- axis swap
- aggregation change
- color / style update
- changing xAxis or yAxis to another existing column from available_columns (view-only)
- ADD a new chart (view-only, derived from existing data)
- Chart title change and return updated chart title with customTitle key

NEW CHART RULES:
- New chart MUST use available_columns
- New chart MUST be view-level (COUNT / SUM / AVG only)
- New chart MUST NOT modify data or SQL
- Chart id MUST be generated by frontend

NOT ALLOWED:
- data modification
- SQL / DB / rows

NOT ALLOWED (VERY STRICT):
- deleting charts
- removing charts
- hiding charts
- disabling charts
- returning messages implying deletion

If user asks to delete/remove a chart:
You MUST return:

{
  "blocked": true,
  "assistant_message": "Chart deletion is not allowed"
}


VIEW CHANGE RULE:

- Changing xAxis to another column is ALLOWED
- Changing yAxis is ALLOWED ONLY if it remains numeric or uses COUNT aggregation
- Column must exist in available_columns
- This is considered a VIEW-LEVEL change, not data modification


VALIDATION:
- Bar/Line: xAxis = text/date, yAxis = number
- Pie: xAxis = label, yAxis = number

OUTPUT FORMAT (EXACT):

{
  "blocked": false,
  "updates": [
    {
      "chart_id": "",
      "updated_fields": {}
    }
  ],
  "new_charts": [],
  "assistant_message": "A short, clear message describing what was changed for the user"
}


assistant_message RULES:
- MUST be human-readable
- MUST summarize the change
- MUST be based on user instruction
- Examples:
  - "Line color changed to yellow"
  - "Different colors applied for each year"
  - "X and Y axes were swapped"
  - "Aggregation changed to SUM"


If invalid:

{
  "blocked": true,
  "assistant_message": "reason"
}
STYLE RULES (VERY IMPORTANT):

For bar charts:

- If user asks for a single color:
  style.barColor MUST be a string hex color.

- If user asks for different colors per x-axis value:
  style.barColor MUST be an object with this EXACT shape:

  {
    "mapping": {
      "<xAxisValue>": "<hex_color>"
    }
  }

- DO NOT return:
  - palette
  - type
  - gradient
  - arrays
  - nested color objects

- barColor MUST be either:
  string OR object with { mapping }

Violation of this rule is INVALID.
"""


def extract_json(text: str):
    """
    Extract first valid JSON object from LLM response
    """
    try:
        start = text.find("{")
        end = text.rfind("}") + 1
        if start == -1 or end == -1:
            return None
        return json.loads(text[start:end])
    except Exception:
        return None

def modify_chart_controller():
    try:
        payload = request.get_json()

        charts = payload.get("charts")
        user_message = payload.get("user_message")
        # HARD BLOCK: destructive intents (DELETE / REMOVE)
        delete_keywords = [
            "delete",
            "remove",
            "drop",
            "clear",
            "hide",
            "disable"
        ]

        if any(k in user_message.lower() for k in delete_keywords):
            return build_response(
                True,
                "Action blocked",
                200,
                {
                    "blocked": True,
                    "assistant_message": "Chart deletion or removal is not allowed via chat. Please use the UI controls."
                }
            )


        if not charts or not user_message:
            return build_response(False, "Invalid payload", 400)
                #  PRE-VALIDATION: axis swap check
        if "swap" in user_message.lower():
            for chart in charts:
                x = chart.get("xAxis")
                y = chart.get("yAxis")

                if not x:
                    msg = "Axis swap is not possible because xAxis is not defined."
                elif not y:
                    msg = "Axis swap is not possible because yAxis is not defined."
                elif x == y:
                    msg = f"Axis swap is not possible because both xAxis and yAxis are set to '{x}'."
                else:
                    continue  #  valid → allow LLM

                return build_response(
                    True,
                    "AI response",
                    200,
                    {
                        "blocked": True,
                        "assistant_message": msg
                    }
                )

        if "wise" in user_message.lower() or "group by" in user_message.lower():
          for chart in charts:
            requested_col = None

            # naive extraction (safe + simple)
            for col in payload.get("available_columns", []):
                if col["name"] in user_message.lower():
                    requested_col = col
                    break

            if requested_col:
                # VALIDATE
                if chart["type"] in ["bar", "line"]:
                    return build_response(
                        True,
                        f"Chart updated to show {requested_col['name']} wise distribution",
                        200,
                        {
                            "blocked": False,
                            "updates": [
                                {
                                    "chart_id": chart["id"],
                                    "updated_fields": {
                                        "xAxis": requested_col["name"],
                                        "yAxis": chart.get("yAxis"),
                                        "agg": "count"
                                    }
                                }
                            ],
                            "assistant_message": f"Bar chart updated to show {requested_col['name']} wise distribution"
                        }
                    )


        prompt = f"""
{SYSTEM_PROMPT}

CHARTS:
{json.dumps(charts, indent=2)}

USER_MESSAGE:
{user_message}
"""

        llm_raw = call_llm(prompt)

        result = extract_json(llm_raw)
        #  FINAL SAFETY: block delete-like responses from LLM
        if result:
            msg = (result.get("assistant_message") or "").lower()

            if any(w in msg for w in ["remove", "removed", "delete", "deleted", "clear"]):
                return build_response(
                    True,
                    "Action blocked",
                    200,
                    {
                        "blocked": True,
                        "assistant_message": "Chart deletion is not allowed."
                    }
                )

        assistant_msg = result.get("assistant_message") or "AI response"

        if not result:
            return build_response(False, "AI returned invalid JSON", 500)
          
        #  SAFETY NORMALIZATION
        if "new_charts" in result:
            for chart in result["new_charts"]:
                # frontend id generate করবে
                chart.pop("id", None)

        return build_response(True, assistant_msg, 200, result)

    except Exception as e:
        return build_response(False, "AI failed", 500, {
            "error": str(e)
        })
